spring.datasource.url=jdbc:postgresql://localhost:5432/forum
spring.datasource.username=forum
spring.datasource.password=forum

spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true
