/**
 * Semantic Design Tokens
 *
 * Maps human-readable token names to MUI CSS variable strings. Use these
 * whenever you need colour values outside of MUI's `sx` prop or component
 * system (e.g. vanilla CSS-in-JS, inline styles, SVG fill attributes).
 *
 * Usage:
 *   import { tokens } from '~/lib/tokens';
 *
 *   // In sx prop (MUI resolves CSS vars automatically):
 *   <Box sx={{ backgroundColor: tokens.color.surface }} />
 *
 *   // In plain CSS-in-JS string:
 *   const style = { background: `var(${tokens.color.surface})` };
 *
 * Token names follow a three-tier hierarchy:
 *   tokens.color.<category>.<variant?>
 *
 * All values are CSS custom property names (--mui-palette-...) generated by
 * MUI's cssVariables API. They resolve to the correct light/dark value
 * automatically based on the data-mui-color-scheme attribute on <html>.
 */

export const tokens = {
  color: {
    // ── Page structure ──────────────────────────────────────────────────────
    /** Page background (slate-50 light / slate-900 dark) */
    background: 'var(--mui-palette-background-default)',
    /** Card / modal / panel surface (white / slate-800) */
    surface: 'var(--mui-palette-background-paper)',

    // ── Text ────────────────────────────────────────────────────────────────
    /** High-emphasis body copy (slate-900 / slate-100) */
    textPrimary: 'var(--mui-palette-text-primary)',
    /** Low-emphasis labels, timestamps, meta (slate-600 / slate-400) */
    textSecondary: 'var(--mui-palette-text-secondary)',
    /** Disabled control labels */
    textDisabled: 'var(--mui-palette-text-disabled)',

    // ── Brand ────────────────────────────────────────────────────────────────
    /** Primary action colour (indigo-600 / indigo-400) */
    primary: 'var(--mui-palette-primary-main)',
    /** Lighter primary — tinted surfaces, hover states */
    primaryLight: 'var(--mui-palette-primary-light)',
    /** Darker primary — pressed/active states */
    primaryDark: 'var(--mui-palette-primary-dark)',
    /** Text/icon colour on primary-filled backgrounds */
    primaryContrast: 'var(--mui-palette-primary-contrastText)',

    /** Secondary accent (violet-600 / violet-400) */
    secondary: 'var(--mui-palette-secondary-main)',
    secondaryLight: 'var(--mui-palette-secondary-light)',
    secondaryDark: 'var(--mui-palette-secondary-dark)',
    secondaryContrast: 'var(--mui-palette-secondary-contrastText)',

    // ── Borders & chrome ─────────────────────────────────────────────────────
    /**
     * Dividers between sections (slate-200 light / slate-700 dark).
     * Use for hr, table rows, list item separators.
     */
    border: 'var(--mui-palette-divider)',

    // ── Semantic status ──────────────────────────────────────────────────────
    success: 'var(--mui-palette-success-main)',
    successLight: 'var(--mui-palette-success-light)',
    successContrast: 'var(--mui-palette-success-contrastText)',

    warning: 'var(--mui-palette-warning-main)',
    warningLight: 'var(--mui-palette-warning-light)',
    warningContrast: 'var(--mui-palette-warning-contrastText)',

    error: 'var(--mui-palette-error-main)',
    errorLight: 'var(--mui-palette-error-light)',
    errorContrast: 'var(--mui-palette-error-contrastText)',

    info: 'var(--mui-palette-info-main)',
    infoLight: 'var(--mui-palette-info-light)',
    infoContrast: 'var(--mui-palette-info-contrastText)',

    // ── Interactive states ────────────────────────────────────────────────────
    /** Hover overlay (translucent indigo tint) */
    hoverOverlay: 'var(--mui-palette-action-hover)',
    /** Selected/active overlay */
    selectedOverlay: 'var(--mui-palette-action-selected)',
    /** Focus ring overlay */
    focusOverlay: 'var(--mui-palette-action-focus)',
  },
} as const;

/** Token key type — useful for typed prop/variant maps in components */
export type ColorToken = keyof typeof tokens.color;
